### ISSUE TITLE
inputs in FireFox

### ISSUE THREAD

**Issue by sirmilord** [AcidHardcore/AdaptUI#1]
![default](https://user-images.githubusercontent.com/25770448/39930271-efc45128-5542-11e8-96b3-2e08ebae69ff.png)

**Comment by sirmilord** [comment]
Take icons from font awesome.io, or use vector svg (ex https://fontawesome.com/icons/user?style=solid)

**Comment by AcidHardcore** [comment]
disappeared after changing classes to bootstrap
